### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by stevefaulkner** [eunjae-lee/issue-to-markdown#16]
hi, this was working fine yesterday, then i started to get this error:
Run eunjae-lee/issue-to-markdown@v[1](https://github.com/stevefaulkner/test_template/actions/runs/7365060416/job/20046014206#step:3:1)

/home/runner/work/_actions/eunjae-lee/issue-to-markdown/v1/webpack:/issue-to-markdown/node_modules/got/index.js:482
			proxy.emit('error', new got.HTTPError(statusCode, res.statusMessage, res.headers, opts), null, res);
^
HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/runner/work/_actions/eunjae-lee/issue-to-markdown/v1/webpack:/issue-to-markdown/node_modules/got/index.js:482:1)
    at EventEmitter.emit (node:events:513:28)
    at getResponse (/home/runner/work/_actions/eunjae-lee/issue-to-markdown/v1/webpack:/issue-to-markdown/node_modules/got/index.js:320:1)
    at Immediate.<anonymous> (/home/runner/work/_actions/eunjae-lee/issue-to-markdown/v1/webpack:/issue-to-markdown/node_modules/got/index.js:147:1)
    at processImmediate (node:internal/timers:466:[21](https://github.com/stevefaulkner/test_template/actions/runs/7365060416/job/20046014206#step:3:22))

![output](https://github.com/eunjae-lee/issue-to-markdown/assets/835859/4468523b-53a2-4368-a544-4ea9f9fa1cf7)

**Comment by eunjae-lee** [comment]
Hi @stevefaulkner thanks for reporting.
As you can see, there hasn't been any activity in this repository lately. It's weird that it just stopped working. Perhaps GitHub had some downtime? Could you try it again and see if it still doesn't work?

**Comment by stevefaulkner** [comment]
@eunjae-lee just tried it again same issue

**Comment by eunjae-lee** [comment]
@stevefaulkner I just tried it here and it worked

- action: https://github.com/eunjae-lee/issue-to-markdown/actions/runs/7384649558/job/20087944759
- commit: https://github.com/eunjae-lee/issue-to-markdown/commit/feee349701ed2ce43227ef1511c45fb6b632c3c2

Could you create a reproducible project? Otherwise, unfortunately I cannot help you. Something is giving you "404 not found" error, but I don't know what that is. If this GitHub Action has its own server, then it would've been the root cause, but it doesn't. So I don't know where to dig.

**Comment by stevefaulkner** [comment]
Hi @eunjae-lee here you go [https://github.com/stevefaulkner/test_template](https://github.com/stevefaulkner/test_template) thanks for looking

**Comment by stevefaulkner** [comment]
@eunjae-lee made the repo public instead of private and it appears to be working

**Comment by eunjae-lee** [comment]
Hi @stevefaulkner I cannot open the repo.

![Screenshot 2024-01-02 at 14 38 56](https://github.com/eunjae-lee/issue-to-markdown/assets/499898/ced87410-7dc3-4ea7-bb54-b6df76691685)

**Comment by stevefaulkner** [comment]
@eunjae-lee  apologies https://github.com/stevefaulkner/test2

**Comment by eunjae-lee** [comment]
@stevefaulkner 

I cannot reproduce it. I forked your repo, added `TOOT` secret of my own, and it's working.

- test issue: https://github.com/eunjae-lee/issue-to-markdown-test/issues/1
- its action: https://github.com/eunjae-lee/issue-to-markdown-test/actions/runs/7387617963/job/20096694672
- output commit: https://github.com/eunjae-lee/issue-to-markdown-test/commit/ed4bc16474f47dd4ff037ca739f0d860de9852da

And looking at your test2 repo, I think it's actually working there, isn't it?

https://github.com/stevefaulkner/test2/commits/main/

![Screenshot 2024-01-02 at 16 42 20](https://github.com/eunjae-lee/issue-to-markdown/assets/499898/5d5060a6-eb0d-4192-8bd3-ded8f316ed0b)

these commits are added by `issue-to-markdown`.

**Comment by stevefaulkner** [comment]
@eunjae-lee yes it is working when the repo is public, the problem occurs when the repo is private

**Comment by eunjae-lee** [comment]
Hi @stevefaulkner, I just made it a private repo, and it worked well. I'm not sure how to reproduce this issue.

Did you create a personal access token like this? ↓
![image](https://github.com/eunjae-lee/issue-to-markdown/assets/499898/c26a283d-5acd-4c45-82ed-d2e6685bc001)

**Comment by stevefaulkner** [comment]
@eunjae-lee thanks for looking into it, will check the token
